name: traffic-collisions

dependencies:
  - python=3.10
  - numpy=1.24
  - pandas=1.5
  - matplotlib=3.6
  - ipython=8.8
  - ipykernel=6.19
  - decorator=5.1
  - scipy=1.8
  - seaborn=0.12.2
  - openpyxl=3.1.2
  - plotly=5.12
  - nbformat=5.8